[package]
name = "embedded-websocket"
version = "0.8.0"
authors = ["David Haig"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ninjasource/embedded-websockets.git"
description = "A lightweight websocket library for embedded systems (no_std)"
keywords = ["websockets", "websocket", "embedded", "no_std"]
categories = ["embedded", "no-std", "network-programming"]
readme = "README.md"

[dependencies]
sha1 = "0.6"
heapless = "0.5"
byteorder = { version = "1.4", default-features = false }
httparse = { version = "1.4", default-features = false }
rand_core = "0.6"
smoltcp = { version = "0.7.1", default-features = false, features = ["socket-tcp", "ethernet", "proto-dhcpv4", "proto-ipv4" ], optional=true }

[dev-dependencies]
rand = "0.8.3"

# see readme for no_std support
[features]
default = ["std"]
# default = []
std = []
smoltcp_support = ["smoltcp"]